<a href="https://colab.research.google.com/github/Ajaysahu01/DATA-ANALYSIS-PROJECTS-ON-PYTHON/blob/main/daily_steps_count_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
daily_steps  = np.random.randint(1000,30000,(1500,7))
daily_steps

array([[18988, 25795,  8344, ...,  9373, 20181,  2301],
       [ 2831, 23101, 16771, ...,  9559,  1329, 25341],
       [19417, 20478, 12469, ...,  7419, 11860, 25427],
       ...,
       [ 6345,  4115, 23293, ..., 18382, 16684, 21411],
       [18798, 11709, 11314, ..., 21364,  6542, 18347],
       [ 4124,  9381, 20690, ..., 15793, 26570, 19538]])

In [ ]:
daily_steps_count = pd.DataFrame(daily_steps)
name = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
daily_steps_count.columns = name
daily_steps_count

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
0      18988   25795     8344      16270      9373   20181      2301
1       2831   23101    16771       4439      9559    1329     25341
2      19417   20478    12469      13065      7419   11860     25427
3      18755   25227    13470       6342     10551   15710     20906
4      14886   24237    26853      29936      1905   17157     19207
...      ...     ...      ...        ...       ...     ...       ...
1495   19566   10110    20747       1008     10276   21898      8571
1496   25618   25213    18005      20621      9735   18151     21787
1497    6345    4115    23293      14744     18382   16684     21411
1498   18798   11709    11314      25224     21364    6542     18347
1499    4124    9381    20690       6633     15793   26570     19538

[1500 rows x 7 columns]

In [ ]:
daily_steps_count.size

10500

In [ ]:
daily_steps_count.shape

(1500, 7)

In [ ]:
daily_steps_count.ndim

2

In [ ]:
daily_steps_count.index

RangeIndex(start=0, stop=1500, step=1)

In [ ]:
daily_steps_count.isnull().sum()

sunday       0
monday       0
tuesday      0
wednesday    0
thursday     0
friday       0
saturday     0
dtype: int64

In [ ]:
#total steps
daily_steps_count.sum()

sunday       23068082
monday       23454839
tuesday      22980144
wednesday    23108870
thursday     23252047
friday       23168016
saturday     23026235
dtype: int64

In [ ]:
#average
daily_steps_count.mean()

sunday       15378.721333
monday       15636.559333
tuesday      15320.096000
wednesday    15405.913333
thursday     15501.364667
friday       15445.344000
saturday     15350.823333
dtype: float64

In [ ]:
#median
daily_steps_count.median()

sunday       14888.0
monday       16220.0
tuesday      15042.5
wednesday    15419.0
thursday     15498.5
friday       15529.5
saturday     15064.0
dtype: float64

In [ ]:
#highest steps count
daily_steps_count.max()

sunday       29972
monday       29989
tuesday      29956
wednesday    29978
thursday     29973
friday       29971
saturday     29968
dtype: int64

In [ ]:
#lowest steps count
daily_steps_count.min()

sunday       1021
monday       1021
tuesday      1049
wednesday    1003
thursday     1010
friday       1022
saturday     1010
dtype: int64

In [ ]:
#top 10 highest count
daily_steps_count.nlargest(10, columns=['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'])

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
497    29972   13246    12525      23234     12618   11180     27838
255    29952    2010    22608      12512     25273    9123     25519
1016   29941   25425    25779      20070     22743    2342     21743
625    29932   28463    27425      14490     25170   29578     12853
472    29927   10124    17510      19683     27048   19131     29775
1131   29897    8191    21009       5781     27169   16536     18437
824    29878   15792    11583       1870     20215   15895     24968
813    29851    9189     6355      22134     18304   27281      6106
1272   29850   17900    18314       2250      1674   13153     14522
979    29850   16383    15870      20742     23633   28924     26579

In [ ]:
#bottom 10 highest count
daily_steps_count.nsmallest(10, columns=['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'])

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
899     1021   20208    24485      10401     25396   10492     12036
1288    1021   22337     5804      25691     21445   24557     21348
812     1079    7184    24885      25934     11842    1911     24315
1307    1092    7224    23721       5980     26103   23507     21871
1202    1106   12651    15731       2123     22952   25948     21382
257     1118   15001    26642      23556     19348   11620      8691
431     1132   22584     3921      27803     17872   18963      1146
1241    1141   14116    13479       6396     14502    4526      6339
1244    1147   12608    13767       4801     15506    9791      4474
1082    1150    8267     7214      11551     26511    6685      1229

In [ ]:
#count days more than 10000 steps
daily_steps_count[daily_steps_count > 10000]

       sunday   monday  tuesday  wednesday  thursday   friday  saturday
0     18988.0  25795.0      NaN    16270.0       NaN  20181.0       NaN
1         NaN  23101.0  16771.0        NaN       NaN      NaN   25341.0
2     19417.0  20478.0  12469.0    13065.0       NaN  11860.0   25427.0
3     18755.0  25227.0  13470.0        NaN   10551.0  15710.0   20906.0
4     14886.0  24237.0  26853.0    29936.0       NaN  17157.0   19207.0
...       ...      ...      ...        ...       ...      ...       ...
1495  19566.0  10110.0  20747.0        NaN   10276.0  21898.0       NaN
1496  25618.0  25213.0  18005.0    20621.0       NaN  18151.0   21787.0
1497      NaN      NaN  23293.0    14744.0   18382.0  16684.0   21411.0
1498  18798.0  11709.0  11314.0    25224.0   21364.0      NaN   18347.0
1499      NaN      NaN  20690.0        NaN   15793.0  26570.0   19538.0

[1500 rows x 7 columns]

In [ ]:
daily_steps_count[daily_steps_count > 10000].count()

sunday       1035
monday       1037
tuesday      1004
wednesday    1028
thursday     1043
friday       1032
saturday     1030
dtype: int64

In [ ]:
#steps less than 5000
daily_steps_count[daily_steps_count < 5000]

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
0        NaN     NaN      NaN        NaN       NaN     NaN    2301.0
1     2831.0     NaN      NaN     4439.0       NaN  1329.0       NaN
2        NaN     NaN      NaN        NaN       NaN     NaN       NaN
3        NaN     NaN      NaN        NaN       NaN     NaN       NaN
4        NaN     NaN      NaN        NaN    1905.0     NaN       NaN
...      ...     ...      ...        ...       ...     ...       ...
1495     NaN     NaN      NaN     1008.0       NaN     NaN       NaN
1496     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1497     NaN  4115.0      NaN        NaN       NaN     NaN       NaN
1498     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1499  4124.0     NaN      NaN        NaN       NaN     NaN       NaN

[1500 rows x 7 columns]

In [ ]:
daily_steps_count[daily_steps_count < 5000].count()

sunday       190
monday       219
tuesday      228
wednesday    213
thursday     206
friday       210
saturday     202
dtype: int64

In [ ]:
#count days between 7000 to 12000
daily_steps_count[(daily_steps_count > 7000) & (daily_steps_count < 12000)]

      sunday   monday  tuesday  wednesday  thursday   friday  saturday
0        NaN      NaN   8344.0        NaN    9373.0      NaN       NaN
1        NaN      NaN      NaN        NaN    9559.0      NaN       NaN
2        NaN      NaN      NaN        NaN    7419.0  11860.0       NaN
3        NaN      NaN      NaN        NaN   10551.0      NaN       NaN
4        NaN      NaN      NaN        NaN       NaN      NaN       NaN
...      ...      ...      ...        ...       ...      ...       ...
1495     NaN  10110.0      NaN        NaN   10276.0      NaN    8571.0
1496     NaN      NaN      NaN        NaN    9735.0      NaN       NaN
1497     NaN      NaN      NaN        NaN       NaN      NaN       NaN
1498     NaN  11709.0  11314.0        NaN       NaN      NaN       NaN
1499     NaN   9381.0      NaN        NaN       NaN      NaN       NaN

[1500 rows x 7 columns]

In [ ]:
daily_steps_count[(daily_steps_count > 7000) & (daily_steps_count < 12000)].count()

sunday       280
monday       261
tuesday      248
wednesday    249
thursday     280
friday       269
saturday     274
dtype: int64

In [ ]:
#percentage of days above 10000 steps
daily_steps_count[daily_steps_count > 10000].count()/daily_steps_count.count()*100

sunday       69.000000
monday       69.133333
tuesday      66.933333
wednesday    68.533333
thursday     69.533333
friday       68.800000
saturday     68.666667
dtype: float64

In [ ]:
#steps greater than average
daily_steps_count.mean()

sunday       15378.721333
monday       15636.559333
tuesday      15320.096000
wednesday    15405.913333
thursday     15501.364667
friday       15445.344000
saturday     15350.823333
dtype: float64

In [ ]:
daily_steps_count[daily_steps_count > daily_steps_count.mean()]

       sunday   monday  tuesday  wednesday  thursday   friday  saturday
0     18988.0  25795.0      NaN    16270.0       NaN  20181.0       NaN
1         NaN  23101.0  16771.0        NaN       NaN      NaN   25341.0
2     19417.0  20478.0      NaN        NaN       NaN      NaN   25427.0
3     18755.0  25227.0      NaN        NaN       NaN  15710.0   20906.0
4         NaN  24237.0  26853.0    29936.0       NaN  17157.0   19207.0
...       ...      ...      ...        ...       ...      ...       ...
1495  19566.0      NaN  20747.0        NaN       NaN  21898.0       NaN
1496  25618.0  25213.0  18005.0    20621.0       NaN  18151.0   21787.0
1497      NaN      NaN  23293.0        NaN   18382.0  16684.0   21411.0
1498  18798.0      NaN      NaN    25224.0   21364.0      NaN   18347.0
1499      NaN      NaN  20690.0        NaN   15793.0  26570.0   19538.0

[1500 rows x 7 columns]

In [ ]:
#steps less than median
daily_steps_count.median()

sunday       14888.0
monday       16220.0
tuesday      15042.5
wednesday    15419.0
thursday     15498.5
friday       15529.5
saturday     15064.0
dtype: float64

In [ ]:
daily_steps_count[daily_steps_count > daily_steps_count.median()]

       sunday   monday  tuesday  wednesday  thursday   friday  saturday
0     18988.0  25795.0      NaN    16270.0       NaN  20181.0       NaN
1         NaN  23101.0  16771.0        NaN       NaN      NaN   25341.0
2     19417.0  20478.0      NaN        NaN       NaN      NaN   25427.0
3     18755.0  25227.0      NaN        NaN       NaN  15710.0   20906.0
4         NaN  24237.0  26853.0    29936.0       NaN  17157.0   19207.0
...       ...      ...      ...        ...       ...      ...       ...
1495  19566.0      NaN  20747.0        NaN       NaN  21898.0       NaN
1496  25618.0  25213.0  18005.0    20621.0       NaN  18151.0   21787.0
1497      NaN      NaN  23293.0        NaN   18382.0  16684.0   21411.0
1498  18798.0      NaN      NaN    25224.0   21364.0      NaN   18347.0
1499      NaN      NaN  20690.0        NaN   15793.0  26570.0   19538.0

[1500 rows x 7 columns]

In [ ]:
# index of the most active day
daily_steps_count.nlargest(1, columns=['sunday','monday','tuesday','wednesday','thursday','friday','saturday']).index

Index([497], dtype='int64')

In [ ]:
# index of the most active day
daily_steps_count.nsmallest(1, columns=['sunday','monday','tuesday','wednesday','thursday','friday','saturday']).index

Index([899], dtype='int64')

In [ ]:
#sort in ascending order
daily_steps_count.sort_values(by=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'])

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
899     1021   20208    24485      10401     25396   10492     12036
1288    1021   22337     5804      25691     21445   24557     21348
812     1079    7184    24885      25934     11842    1911     24315
1307    1092    7224    23721       5980     26103   23507     21871
1202    1106   12651    15731       2123     22952   25948     21382
...      ...     ...      ...        ...       ...     ...       ...
472    29927   10124    17510      19683     27048   19131     29775
625    29932   28463    27425      14490     25170   29578     12853
1016   29941   25425    25779      20070     22743    2342     21743
255    29952    2010    22608      12512     25273    9123     25519
497    29972   13246    12525      23234     12618   11180     27838

[1500 rows x 7 columns]

In [ ]:
#sort in descending order
daily_steps_count.sort_values(by=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'], ascending=False)

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
497    29972   13246    12525      23234     12618   11180     27838
255    29952    2010    22608      12512     25273    9123     25519
1016   29941   25425    25779      20070     22743    2342     21743
625    29932   28463    27425      14490     25170   29578     12853
472    29927   10124    17510      19683     27048   19131     29775
...      ...     ...      ...        ...       ...     ...       ...
1202    1106   12651    15731       2123     22952   25948     21382
1307    1092    7224    23721       5980     26103   23507     21871
812     1079    7184    24885      25934     11842    1911     24315
1288    1021   22337     5804      25691     21445   24557     21348
899     1021   20208    24485      10401     25396   10492     12036

[1500 rows x 7 columns]

In [ ]:
# difference between the most and least active days
daily_steps_count.max() - daily_steps_count.min()

sunday       28951
monday       28968
tuesday      28907
wednesday    28975
thursday     28963
friday       28949
saturday     28958
dtype: int64

In [ ]:
#increase steps by 15%
increase= daily_steps_count * 1.15
increase

        sunday    monday   tuesday  wednesday  thursday    friday  saturday
0     21836.20  29664.25   9595.60   18710.50  10778.95  23208.15   2646.15
1      3255.65  26566.15  19286.65    5104.85  10992.85   1528.35  29142.15
2     22329.55  23549.70  14339.35   15024.75   8531.85  13639.00  29241.05
3     21568.25  29011.05  15490.50    7293.30  12133.65  18066.50  24041.90
4     17118.90  27872.55  30880.95   34426.40   2190.75  19730.55  22088.05
...        ...       ...       ...        ...       ...       ...       ...
1495  22500.90  11626.50  23859.05    1159.20  11817.40  25182.70   9856.65
1496  29460.70  28994.95  20705.75   23714.15  11195.25  20873.65  25055.05
1497   7296.75   4732.25  26786.95   16955.60  21139.30  19186.60  24622.65
1498  21617.70  13465.35  13011.10   29007.60  24568.60   7523.30  21099.05
1499   4742.60  10788.15  23793.50    7627.95  18161.95  30555.50  22468.70

[1500 rows x 7 columns]

In [ ]:
#new average
increase.mean()

sunday       17685.529533
monday       17982.043233
tuesday      17618.110400
wednesday    17716.800333
thursday     17826.569367
friday       17762.145600
saturday     17653.446833
dtype: float64

In [ ]:
#cross 10000 steps after increase by 15%
increase[increase > 10000]

        sunday    monday   tuesday  wednesday  thursday    friday  saturday
0     21836.20  29664.25       NaN   18710.50  10778.95  23208.15       NaN
1          NaN  26566.15  19286.65        NaN  10992.85       NaN  29142.15
2     22329.55  23549.70  14339.35   15024.75       NaN  13639.00  29241.05
3     21568.25  29011.05  15490.50        NaN  12133.65  18066.50  24041.90
4     17118.90  27872.55  30880.95   34426.40       NaN  19730.55  22088.05
...        ...       ...       ...        ...       ...       ...       ...
1495  22500.90  11626.50  23859.05        NaN  11817.40  25182.70       NaN
1496  29460.70  28994.95  20705.75   23714.15  11195.25  20873.65  25055.05
1497       NaN       NaN  26786.95   16955.60  21139.30  19186.60  24622.65
1498  21617.70  13465.35  13011.10   29007.60  24568.60       NaN  21099.05
1499       NaN  10788.15  23793.50        NaN  18161.95  30555.50  22468.70

[1500 rows x 7 columns]

In [ ]:
#90TH PERCENTILE STEPS
daily_steps_count.quantile(0.9)

sunday       27070.6
monday       27102.4
tuesday      27486.0
wednesday    27035.2
thursday     27046.2
friday       26941.2
saturday     26989.8
Name: 0.9, dtype: float64

In [ ]:
#10TH PERCENTILE STEPS
daily_steps_count.quantile(0.1)

sunday       4089.4
monday       3704.0
tuesday      3579.7
wednesday    3664.0
thursday     4081.2
friday       4020.4
saturday     4042.6
Name: 0.1, dtype: float64

In [ ]:
#HOW MANY DAYS ARE ABOVE 90TH PERCENTILE
daily_steps_count[daily_steps_count > daily_steps_count.quantile(0.9)]

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
0        NaN     NaN      NaN        NaN       NaN     NaN       NaN
1        NaN     NaN      NaN        NaN       NaN     NaN       NaN
2        NaN     NaN      NaN        NaN       NaN     NaN       NaN
3        NaN     NaN      NaN        NaN       NaN     NaN       NaN
4        NaN     NaN      NaN    29936.0       NaN     NaN       NaN
...      ...     ...      ...        ...       ...     ...       ...
1495     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1496     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1497     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1498     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1499     NaN     NaN      NaN        NaN       NaN     NaN       NaN

[1500 rows x 7 columns]

In [ ]:
daily_steps_count[daily_steps_count > daily_steps_count.quantile(0.9)].count()

sunday       150
monday       150
tuesday      150
wednesday    150
thursday     150
friday       150
saturday     150
dtype: int64

In [ ]:
#HOW MANY DAYS ARE BELOW 10TH PERCENTILE
daily_steps_count[daily_steps_count < daily_steps_count.quantile(0.1)]

      sunday  monday  tuesday  wednesday  thursday  friday  saturday
0        NaN     NaN      NaN        NaN       NaN     NaN    2301.0
1     2831.0     NaN      NaN        NaN       NaN  1329.0       NaN
2        NaN     NaN      NaN        NaN       NaN     NaN       NaN
3        NaN     NaN      NaN        NaN       NaN     NaN       NaN
4        NaN     NaN      NaN        NaN    1905.0     NaN       NaN
...      ...     ...      ...        ...       ...     ...       ...
1495     NaN     NaN      NaN     1008.0       NaN     NaN       NaN
1496     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1497     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1498     NaN     NaN      NaN        NaN       NaN     NaN       NaN
1499     NaN     NaN      NaN        NaN       NaN     NaN       NaN

[1500 rows x 7 columns]

In [ ]:
daily_steps_count[daily_steps_count < daily_steps_count.quantile(0.1)].count()

sunday       150
monday       149
tuesday      150
wednesday    150
thursday     150
friday       150
saturday     150
dtype: int64