<a href="https://colab.research.google.com/github/Ajaysahu01/DATA-ANALYSIS-PROJECTS-ON-PYTHON/blob/main/project_students_marks_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
mark = np.random.randint(33,101,[1000,5])
marks = pd.DataFrame(marks, columns = ["maths","english","science","hindi","computer"])

marks

     maths  english  science  hindi  computer
0       83       74       72     77        82
1       64       91       35     48        79
2       34       82       47     65        64
3       84       69       57     68        95
4       72       91       84     81        55
..     ...      ...      ...    ...       ...
995     68       76       65     71        57
996     51       56       84     87        96
997     43       91       39     37        35
998     42       64       52     78        65
999     81       47       78     54        54

[1000 rows x 5 columns]

In [ ]:
marks.size

5000

In [ ]:
marks.shape

(1000, 5)

In [ ]:
marks.ndim

2

In [ ]:
marks.count()

maths       1000
english     1000
science     1000
hindi       1000
computer    1000
dtype: int64

In [ ]:
marks.values

array([[83, 74, 72, 77, 82],
       [64, 91, 35, 48, 79],
       [34, 82, 47, 65, 64],
       ...,
       [43, 91, 39, 37, 35],
       [42, 64, 52, 78, 65],
       [81, 47, 78, 54, 54]])

In [ ]:
marks.isnull().sum()

maths       0
english     0
science     0
hindi       0
computer    0
dtype: int64

In [ ]:
marks.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
#total marks
marks

     maths  english  science  hindi  computer
0       83       74       72     77        82
1       64       91       35     48        79
2       34       82       47     65        64
3       84       69       57     68        95
4       72       91       84     81        55
..     ...      ...      ...    ...       ...
995     68       76       65     71        57
996     51       56       84     87        96
997     43       91       39     37        35
998     42       64       52     78        65
999     81       47       78     54        54

[1000 rows x 5 columns]

In [ ]:
#average marks
marks.mean()

maths       65.620
english     67.610
science     65.917
hindi       67.026
computer    65.596
dtype: float64

In [ ]:
#highest marks
marks.max()

maths       100
english     100
science     100
hindi       100
computer    100
dtype: int64

In [ ]:
#lowest marks
marks.min()

maths       33
english     33
science     33
hindi       33
computer    33
dtype: int64

In [ ]:
# marks more than or equal to 80
marks[marks >= 80]

     maths  english  science  hindi  computer
0     83.0      NaN      NaN    NaN      82.0
1      NaN     91.0      NaN    NaN       NaN
2      NaN     82.0      NaN    NaN       NaN
3     84.0      NaN      NaN    NaN      95.0
4      NaN     91.0     84.0   81.0       NaN
..     ...      ...      ...    ...       ...
995    NaN      NaN      NaN    NaN       NaN
996    NaN      NaN     84.0   87.0      96.0
997    NaN     91.0      NaN    NaN       NaN
998    NaN      NaN      NaN    NaN       NaN
999   81.0      NaN      NaN    NaN       NaN

[1000 rows x 5 columns]

In [ ]:
marks[marks >= 80].count()

maths       274
english     341
science     304
hindi       301
computer    280
dtype: int64

In [ ]:
#students failed in each subject
#passing marks =45
marks[marks<45]

     maths  english  science  hindi  computer
0      NaN      NaN      NaN    NaN       NaN
1      NaN      NaN     35.0    NaN       NaN
2     34.0      NaN      NaN    NaN       NaN
3      NaN      NaN      NaN    NaN       NaN
4      NaN      NaN      NaN    NaN       NaN
..     ...      ...      ...    ...       ...
995    NaN      NaN      NaN    NaN       NaN
996    NaN      NaN      NaN    NaN       NaN
997   43.0      NaN     39.0   37.0      35.0
998   42.0      NaN      NaN    NaN       NaN
999    NaN      NaN      NaN    NaN       NaN

[1000 rows x 5 columns]

In [ ]:
marks[marks<45].count()

maths       183
english     165
science     199
hindi       163
computer    195
dtype: int64

In [ ]:
# top 10 student marks
marks.head(10)

   maths  english  science  hindi  computer  total
0     50       65       88     52        49    304
1     56       96       89     49        86    376
2     58       99       40     98        59    354
3     97       37       51     89        98    372
4     80       56       54     73        79    342
5     64       88       89     55        40    336
6     63       35       41     77        77    293
7     98       90       57     73        46    364
8    100       39       42     59        37    277
9     76       68       59     63        89    355

In [ ]:
#bottom 10 student marks
marks.tail(10)

     maths  english  science  hindi  computer
990     93       64       50     33        76
991    100       62       75     36        86
992     51       77       38     66        39
993     56       33       96     37        76
994     55       98       72     46        62
995     68       76       65     71        57
996     51       56       84     87        96
997     43       91       39     37        35
998     42       64       52     78        65
999     81       47       78     54        54

In [ ]:
#marks scored between 60 and 80
marks[(marks>60) & (marks<80)]

     maths  english  science  hindi  computer
0      NaN     74.0     72.0   77.0       NaN
1     64.0      NaN      NaN    NaN      79.0
2      NaN      NaN      NaN   65.0      64.0
3      NaN     69.0      NaN   68.0       NaN
4     72.0      NaN      NaN    NaN       NaN
..     ...      ...      ...    ...       ...
995   68.0     76.0     65.0   71.0       NaN
996    NaN      NaN      NaN    NaN       NaN
997    NaN      NaN      NaN    NaN       NaN
998    NaN     64.0      NaN   78.0      65.0
999    NaN      NaN     78.0    NaN       NaN

[1000 rows x 5 columns]

In [ ]:
# compare the average marks of all the subject of each student
marks

     maths  english  science  hindi  computer
0       50       65       88     52        49
1       56       96       89     49        86
2       58       99       40     98        59
3       97       37       51     89        98
4       80       56       54     73        79
..     ...      ...      ...    ...       ...
995     40       81       60     75        42
996     54       75       51     34        99
997     59       52       71     42        44
998     73       56       98     42        51
999     68       76       77     75        80

[1000 rows x 5 columns]

In [ ]:
marks.mean(axis=0)

maths       67.494
english     66.037
science     65.927
hindi       66.117
computer    66.142
dtype: float64

In [ ]:
# Calculate the average mark of all five subjects for each individual student
marks.mean(axis=1)

0      60.8
1      75.2
2      70.8
3      74.4
4      68.4
       ...
995    59.6
996    62.6
997    53.6
998    64.0
999    75.2
Length: 1000, dtype: float64